[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-cors = "0.6.1"
redis = {version = "0.21.5", features = ["tokio-comp", "connection-manager"]}
redis_ts = { version = "0.4.1", features = ['tokio-comp'] }
env_logger = "0.9.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.59"